version: '3.1'

services:

  postgres:
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./01_dept.sql:/docker-entrypoint-initdb.d/01_dept.sql
      - ./02_emp.sql:/docker-entrypoint-initdb.d/02_emp.sql
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    restart: unless-stopped
    ports:
      - "54322:5432"
    environment:
        - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
        - "POSTGRES_DB=${POSTGRES_DB}"

  adminer:
    image: adminer
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    restart: unless-stopped
    ports:
      - 8099:8080